# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
  - page: home
    url: /Live-the-Life/
    icon: 


## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: 
  url: 

# 各个小工具的设置

## widgets
widgets:
  - category
  - tagcloud
  - archive
  - social


## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: true
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 网站公告设置
notification: |-
            <p>
                主题下载：<a href="https://github.com/shenliyang/hexo-theme-snippet" title="fork me" target="_blank">Snippet主题</a> <br/>
                主题使用：<a href="https://github.com/shenliyang/hexo-theme-snippet/blob/master/README.md#常见问题" title="" target="_blank">常见使用问题</a> <br/>
                支持主题：<a href="https://github.com/shenliyang/hexo-theme-snippet/stargazers">Star一下</a>
            </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/SMartQi

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: true
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
  - Hexo官网: https://hexo.io/zh-cn/


# 主题自定义个性化配置

## 网站宣传语
branding:  "Live the Life"

## 设置banner背景图片
banner:
    img: https://raw.githubusercontent.com/SMartQi/Live-the-Life/master/source/gallery/header.jpg

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      转载请联系作者获得授权

## 文章打赏
reward:
  alipay: ''
  wepay: ''
  tip: 赞赏是不耍流氓的鼓励

## 主题评论

### gitment
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 来必力
livere:
  enable: false
  livere_uid: 

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

## Valine评论
valine:
   enable: false
   appId: 
   appKey: 
   placeholder: 
   notify: false
   verify: false
   avatar: 
   meta: 
   pageSize: 10

## 网站访客统计
visit_counter:
   site: false
   page: false

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: false

#网站主题配置
since: 2017
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1
